version: "3"
services:
  db:
    image: mongo:4.4.6
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "account_stream_data:/data/db"
    networks:
      - account-stream-network
  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - account-stream-network
  app:
    image: account-stream-img:latest
    environment:
      KAFKA_HOST: kafka
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: secret
      DB_NAME: bank
    networks:
      - account-stream-network
    depends_on:
#      - kafka
      - db
    restart: on-failure
volumes:
  account_stream_data:
networks:
  account-stream-network:
    driver: bridge
