spring:
  application:
    name: account-stream
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: America/Sao_Paulo

  # MongoDB
  data:
    mongodb:
      database: bank
      repositories:
        enabled: true
      auto-index-creation: true
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/bank?authSource=admin

  # Kafka
  kafka:
    producer:
      retries: 5
      acks: all

  # Cloud Stream
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          autoAddPartitions: true
          configuration:
            isolation:
              level: read_committed
          brokers: ${KAFKA_HOST}
      function:
        definition: upsertBankAccountPersist;upsertBankAccountEventPersist;transformLegacyBankAccount;transformLegacyBankAccountEvent;transformLegacyBankAccountConnect;transformLegacyBankAccountEventConnect
      bindings:
        upsertBankAccountPersist-in-0:
          destination: account-upsert-bank-account
          group: account-bank-account
        upsertBankAccountPersist-out-0:
          destination: account-upsert-bank-account-success
          group: account-bank-account
          contentType: application/json

        upsertBankAccountEventPersist-in-0:
          destination: account-upsert-bank-account-event
          group: account-bank-account-event
        upsertBankAccountEventPersist-out-0:
          destination: account-upsert-bank-account-event-success
          group: account-bank-account-event
          contentType: application/json

        transformLegacyBankAccount-in-0:
          destination: database-bank-account
          group: account-bank-account
        transformLegacyBankAccount-out-0:
          destination: account-upsert-bank-account
          group: account-bank-account

        transformLegacyBankAccountEvent-in-0:
          destination: database-bank-account-event
          group: account-bank-account-event
        transformLegacyBankAccountEvent-out-0:
          destination: account-upsert-bank-account-event
          group: account-bank-account-event

        transformLegacyBankAccountConnect-in-0:
          destination: postgresql_account
          group: account-bank-account
        transformLegacyBankAccountConnect-out-0:
          destination: account-upsert-bank-account
          group: account-bank-account

        transformLegacyBankAccountEventConnect-in-0:
          destination: postgresql_account_transaction
          group: account-bank-account-event
        transformLegacyBankAccountEventConnect-out-0:
          destination: account-upsert-bank-account-event
          group: account-bank-account-event
